name: Project X
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56451
title: Project X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e412f'
    - '#f0a830'
    - '#f07818'
    - '#78c0a8'
    - '#fcebb6'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
