name: Project X
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41007
title: Project X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5c900'
    - '#e50055'
    - '#3c2b00'
    - '#8a0000'
    - '#b69800'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
